### ISSUE TITLE
Inactive layers

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#148]
![image](https://user-images.githubusercontent.com/178003/150006965-1920e67e-6744-482c-a790-e6a20f79e667.png)

I am unsure why these layers are not active and cannot be shown @meomancer . If there is a valid reason, can you make it so that it is clear for the user why, otherwise can you fix them please?

**Comment by meomancer** [comment]
hi @timlinux 
Updated with the info that why it is disable
![Selection_017](https://user-images.githubusercontent.com/4530905/150071090-c3dd02a8-e144-4208-8757-352c989b02db.png)

This is because the token is invalid
i think the token is renewed

so maybe we can ask them the username/password so we can use that as basic auth (basically the layers i get is from their website which is using token)
