### ISSUE TITLE
Missing values in global report

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#155]
![image](https://user-images.githubusercontent.com/178003/150753919-4e8b0d0d-b72f-4753-83c0-e99b80913bc7.png)

**Comment by meomancer** [comment]
This has been fixed
now it is just showing correct indicator
what it means is for example above picture
Covid Case geometry level report is on Country level and we are looking on District Tab
So that why empty because the data for Covid for district is empty
So it is fixed by removing incorrect indicators
