### ISSUE TITLE
Spreadsheet values blank

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#175]
![imagem](https://user-images.githubusercontent.com/178003/151341005-bebc0406-0f07-46e1-aebe-037c29c48e93.png)

Can you please check through all exporters and ensure they are populated with full data for all geography levels. In this case none of the levels seem to have it.

**Comment by meomancer** [comment]
The problem is because the data is empty in selected date.
So the IDPs does not have data in the selected date

The solution is for now, The download button will be enabled/disabled if the data presented

![Selection_012](https://user-images.githubusercontent.com/4530905/151510219-5224ce5c-89f3-4bb7-8a23-bb0e12b11e55.png)
![Selection_013](https://user-images.githubusercontent.com/4530905/151510226-411995d2-dbc2-45fc-b827-dc1b29c7c433.png)

**Comment by timlinux** [comment]
Ok good thanks
